disabled_rules:
  - line_length
  - variable_name
  - missing_docs
  - type_body_length
  - force_try
opt_in_rules:
  - empty_count
  - closure_spacing
  - missing_docs
  - explicit_init
  - force_unwrapping
  - overridden_super_call
  - redundant_nil_coalesing
  - switch_case_on_newline
file_length:
  warning: 500
  error: 9999
